ArchImpl/RISCV/RISCVArchSpecificImp.h
ArchImpl/RISCV64/RISCV64ArchSpecificImp.h
include/etiss/Misc.h
src/Misc.cpp
src/Translation.cpp

- Architectural JIT libraries initialization by architecture
- Usage in Translation through ETISS config.
Idea: Architecture specifies which additional, or rather extending, libraries should be available in the JIT context.

Dynamic JIT libraries for Translation Unit

---

ArchImpl/RISCV/RISCVArch.cpp
ArchImpl/RISCV64/RISCV64Arch.cpp
JITImpl/TCC/CMakeLists.txt

RISCVArch.cpp and RISCV64Arch.cpp updated to reflect latest changes in M2-ISA-R, removes unnessecary return statements after many instructions.
CMakeLists.txt for TCC is now properly applying optimizations to TCCLib compilation.
Note: Only RISCV (32 bit) is tested, as I do not have a test setup for 64 bit.

Performance Improvements, Round 1

---

.github/workflows/ci.yml
examples/bare_etiss_processor/main.cpp
examples/bare_etiss_processor/run_helper.sh.in

Bare etiss processor will now show error codes by setting a return code on exit along with the error message according to the mapping:
**Error code 0:** Proper execution, no error
**Error code 1:** Targets program error
**Error code 2:** Targets JIT engine error
**Error code 3:** Targets everything else

Allow bare_etiss_processor to report run-time errors to CI

---

ArchImpl/RISCV/RISCVArch.cpp
ArchImpl/RISCV64/RISCV64Arch.cpp

(2nd attempt w/ trailing whitespace issue in staged files)
workaround for #29
core-local [11:0], platform-specific [XLEN-1:12]

enable all RISC-V interrupts by default 

---

JITImpl/GCC/GCCJIT.cpp

If libraries were not loaded properly, GCCJIT gave errors due to missing spaces and options. This is now fixed.

GCCJIT space issue fix

---

examples/bare_etiss_processor/CMakeLists.txt.in
examples/bare_etiss_processor/get_metrics.py
examples/bare_etiss_processor/main.cpp

1. `get_metrics.py` determines `RAM_START`, `RAM_SIZE` and `STACK_SIZE` by parsing the ELF file instead of using constants
2. `main.cpp` uses the pre-processor variables `ROM_START`, `ROM_SIZE`, `RAM_START` and `RAM_SIZE` instead of hardcoded `0x0`, `0x80000`, `0x80000`, `0x80000` which can be overwrite with  CMake variables when building `bare_etiss_processor`.
This allows to change the aforementioned properties without needing to patch files manually and also ensures that the exported memory reports are based on the actual values.

bare_etiss_processor: replace hardcoded memory properties

---

.github/workflows/ci.yml
JITImpl/TCC/TCCJIT.cpp
include/etiss/LibraryInterface.h
src/LibraryInterface.cpp
src/Translation.cpp

This wouldn't really have to be in the translate function, but the constructor is too early to have the library path additions from the Arch plugins.

Fix CI on Windows

---

examples/SW/riscv/README.md

The recommend [toolchain](https://www.sifive.com/software) (`v2020.12.8`) does not seem to support `rv64g`. Only `rv64gc` (i.e. `rv64imfdc`) is supported. 
Invoking `cmake [...] -DRISCV_ARCH=rv64g -DRISCV_ABI=lp64d ..` and then `make` results in: 
```
/home/fabian/master/fp/toolchains/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/../../../../riscv64-unknown-elf/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
```
for me. 
Running `cmake [...] -DRISCV_ARCH=rv64gc -DRISCV_ABI=lp64d ..` and then `make` instead gives no errors.
Running `./riscv64-unknown-elf-gcc --print-multi-lib` gives:
```
.;
rv32ec/ilp32e;@march=rv32ec@mabi=ilp32e
rv32ec_zba_zbb/ilp32e;@march=rv32ec_zba_zbb@mabi=ilp32e …
```

Update README.md with correct RISCV_ARCH (-march) flag

---

examples/bare_etiss_processor/get_metrics.py
examples/bare_etiss_processor/requirements.txt

I have implemented what was beeing discussed in #68 in addition with further smaller improvements to the `get_metrics.py` script.
I had to add the argparse package as a requirement to be able to use optional command line parameters. This should hopefully not break too many existing setups...
For parsing the INI containing the memory layout, I have used the following as a reference. Can I expect that there are always 2 memory segments, the first being for ROM and the other one for RAM? If not, then I am not sure how to find out which one is which...
```
$ cat memsegs.ini
```
BTW: `heapStart` is unfortunately still relying on the symbol table.

Improve get_metrics.py

---

examples/SW/riscv/cmake/PulpinoTarget.cmake

When building multiple targets from a single CMake script using the `ADD_EXECUTABLE_PULPINO` macro, e.g. as follows:
```
...
ADD_EXECUTABLE_PULPINO(riscv_example.elf main.c)
ADD_EXECUTABLE_PULPINO(riscv_example_fancy.elf main.c fancy.c)
...
```
the linker (rightfully) complains about duplicate option definitions. For example the linker script option `-T`:
```
error: linker script file installed/examples/SW/riscv/cmake/pulpino_tumeda/link.ld' appears multiple times
``` 
in `CMAKE_EXE_LINKER_FLAGS`.
@rafzi this is most likely not the prettiest fix, but "minimally invasive".

Prevent linker option duplicates when calling pulpino macro for multiple targets

---

ArchImpl/RISCV/RISCVArch.cpp
ArchImpl/RISCV64/RISCV64Arch.cpp
examples/bare_etiss_processor/ETISS.ini
examples/bare_etiss_processor/base.ini

Resolves Issue #98
Default/Fallback value: 32MHZ as this was used before. However `base.ini` and `ETISS.ini` currently default to 100MHz.

RISCV/RISCV64: Initialize cpuCycleTime_ps with arch.cpu_cycle_time_ps INI option

---

examples/bare_etiss_processor/get_metrics.py
src/SimpleMemSystem.cpp

A recent version of the RISCV GCC Toolchain caused ETISS crashes due to an unexpected new memory segment added to the ELF:
```
Program Headers:
Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
LOPROC+0x3     0x02f113 0x00000000 0x00000000 0x0008f 0x00000 R   0x1
LOAD           0x001000 0x00000000 0x00000000 0x1220c 0x1220c R E 0x1000
LOAD           0x014000 0x00100000 0x00100000 0x009cc 0x08af8 RW  0x1000
Section to Segment mapping:
Segment Sections...
00     .riscv.attributes
01     .vectors .text .text.startup .rodata .eh_frame
02     .init_array .data .sdata .bss .stack
```
This PR adds a check to skip empty segments in the `SimpleMemSystem` (as recommended by @rafzi)

SimpleMemSystem: skip empty elf segments

---

.github/workflows/ci.yml
JITImpl/TCC/CMakeLists.txt
JITImpl/TCC/TCCJIT.cpp

Addresses issue https://github.com/tum-ei-eda/etiss/issues/108
TODO:

fetch and build TCC from github repository

---

CMakeLists.txt
include/etiss/ETISS.h
src/ETISS.cpp

Moving include of external dependency header SimpleIni form ETISS.h to ETISS.cpp where it is actually required.
This allows external programs to use ETISS.h without re-importing SimpleIni.

Code Clean-up: Move include of SimpleIni.h form ETISS.h to ETISS.cpp

---

.github/workflows/docs.yml

GitHub Actions has gained a feature where GitHub Pages hosted content can be deployed directly from an Actions workflow, no separate branch storing documentation data needed. See:
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/
This fixes #83. If we roll out this change, we should also think about removing the `gh-pages` branch along with all commits related to it to reduce the repository size.

Move Doxygen deploy location to GitHub Actions

---

examples/SW/riscv/CMakeLists.txt
examples/SW/riscv/main.c
examples/SW/riscv/test_accelerators/qvanilla_acc.c
examples/SW/riscv/test_accelerators/qvanilla_acc.h
examples/SW/riscv/test_accelerators/vanilla_acc.c
examples/SW/riscv/test_accelerators/vanilla_acc.h
include/etiss/IntegratedLibrary/MemMappedPeriph.h
include/etiss/IntegratedLibrary/QVanillaAccelerator.h
include/etiss/IntegratedLibrary/VanillaAccelerator.h
src/IntegratedLibrary.cpp
src/IntegratedLibrary/QVanillaAccelerator.cpp
src/IntegratedLibrary/VanillaAccelerator.cpp
src/bare_etiss_processor/base.ini

updated the register interface of the "Vanilla" and "QVanilla" accelerators, to resolve sign/unsigned issue. 
the base address of the peripherals can be controlled via ini-file
added "Vanilla" accelerator as 2nd peripheral.
added device code example to use both accelerators.
What might be good, if some error handling/completion signaling can be added in future.

update register interface of accelerators

---

include/etiss/CPUCore.h
include/etiss/IntegratedLibrary/Logger.h
include/etiss/IntegratedLibrary/MemMappedPeriph.h
include/etiss/IntegratedLibrary/SelectiveSysWrapper.h
src/IntegratedLibrary/Logger.cpp
src/IntegratedLibrary/MemMappedPeriph.cpp
src/IntegratedLibrary/SelectiveSysWrapper.cpp

SelectiveSysWrapper: Only wraps some of the System calls to avoid unnecessary intermediate calls.
MemMappedPeriph: Currently unused, but useful as a base for lightweight memory mapped peripherals.
The Logger plugin was changed to use the SelectiveSysWrapper, so that it only has to override the dwrite System call. This improves performance by about 10% while the Logger is active.

add SelectiveSysWrapper and MemMappedPeriph

---

JITImpl/GCC/GCCJIT.cpp

Use `-Wall` flag to print all warnings generated by GCCJIT when `jit.debug=true` to ease debugging.

GCCJIT: enable -Wall flag in debug mode

---

include/etiss/SimpleMemSystem.h
src/SimpleMemSystem.cpp

Delete Buffer in loadsegments function
Initialize memory region with 0 if no image existent

Init each memory region in init script with zero and fix un-freed buffer

---

CMakeLists.txt
cmake/RegisterJITFiles.cmake

Should resolve #156 
Documentation and Example: https://github.com/tum-ei-eda/etiss-arch-plugins

CMake: Support building ArchImpl Plugins out-of-tree

---

.github/workflows/style.yml
src/ETISS.cpp

C/C++ Linting only for now. CMake can follow later.
I went with a less intrusive approach:
- Only changed files are checked
- Linter problems are highlighted/annotated in the Patch, PR Comments are added automatically.
- CI job always succeeds, PRs can still be merged, even if linter is unhappy.
Instead of forcing the style guide on all files at once. This way we can clean up file-by-file as soon as one PR touches them.
From what I have seen so far, running `clang-format` locally, most of the issues are just whitespace or line-length related, hence relatively easy fixes, which can be fixed and applied by running `clang-format -i path/to/file` manually.
Fixes #3

CI: Add Lint Action

---

docs/CONTRIBUTING.adoc

Describes the already in-use simple trunk-based policy.
Will create a "Contributing" tab in the main repository view:

Add CONTRIBUTING Guide
